repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.14.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]


      # - repo: local
      #   hooks:
      #     - id: run-coverage
      #       name: run-coverage
      #       entry: bash -c "coverage run --omit '*/site-packages/*','*/test/*' -m pytest && coverage report -m"
      #       language: system
      #       types: [python]
      #       pass_filenames: false
      #       verbose: true
